openai:
  api_key:
  model: gpt-3.5-turbo
  max_tokens: 1024
  temperature: 0.4
  prompt: Translate the following message to {language} in a conversational style. Write nothing else except this translation.
